name: Build e Validação

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true  # ativa o modo CI para Gradle ignorar Selenium

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permissão ao Gradle
        run: chmod +x gradlew

      - name: Build do projeto
        run: ./gradlew build --no-daemon

      - name: Executar testes
        run: ./gradlew test --no-daemon

      - name: Arquivar resultados de testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: build/reports/tests/test
